-- Northwind Sample Database for Testing
-- Auto-generated by /testsql skill

CREATE DATABASE testdb;
GO

USE testdb;
GO

-- Customers table
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY IDENTITY(1,1),
    CompanyName NVARCHAR(100) NOT NULL,
    ContactName NVARCHAR(100),
    Country NVARCHAR(50),
    CreatedDate DATETIME DEFAULT GETDATE()
);

-- Orders table
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY IDENTITY(1,1),
    CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID),
    OrderDate DATETIME DEFAULT GETDATE(),
    TotalAmount DECIMAL(10,2)
);

-- Products table
CREATE TABLE Products (
    ProductID INT PRIMARY KEY IDENTITY(1,1),
    ProductName NVARCHAR(100) NOT NULL,
    UnitPrice DECIMAL(10,2),
    UnitsInStock INT DEFAULT 0
);

-- Sample data
INSERT INTO Customers (CompanyName, ContactName, Country) VALUES
('Contoso Ltd', 'John Doe', 'USA'),
('Fabrikam Inc', 'Jane Smith', 'Canada'),
('Adventure Works', 'Bob Johnson', 'UK'),
('Northwind Traders', 'Alice Williams', 'Germany');

INSERT INTO Products (ProductName, UnitPrice, UnitsInStock) VALUES
('Widget', 9.99, 100),
('Gadget', 19.99, 50),
('Doohickey', 14.99, 75),
('Thingamajig', 24.99, 30);

INSERT INTO Orders (CustomerID, OrderDate, TotalAmount) VALUES
(1, '2026-01-15', 1500.00),
(1, '2026-01-20', 2300.50),
(2, '2026-01-18', 750.25),
(3, '2026-01-22', 980.00);

PRINT 'Northwind sample database created successfully';
GO
